In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
pd.set_option('display.max_rows',80)
pd.set_option('display.max_columns',80)
pd.set_option('max_colwidth',300)

In [4]:
data=pd.read_csv('ibm employees.csv')
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [5]:
data.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,2.728571,6502.931293,14313.103401,2.693197,15.209524,3.153741,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,1.102846,4707.956783,7117.786044,2.498009,3.659938,0.360824,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1009.000000,2094.000000,0.000000,11.000000,3.000000,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,2.000000,2911.000000,8047.000000,1.000000,12.000000,3.000000,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,3.000000,4919.000000,14235.500000,2.000000,14.000000,3.000000,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,4.000000,8379.000000,20461.500000,4.000000,18.000000,3.000000,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,19999.000000,26999.000000,9.000000,25.000000,4.000000,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [6]:
data.JobLevel.value_counts()

1    543
2    534
3    218
4    106
5     69
Name: JobLevel, dtype: int64

In [7]:
data.StandardHours.value_counts()

80    1470
Name: StandardHours, dtype: int64

In [8]:
data.StockOptionLevel.value_counts()

0    631
1    596
2    158
3     85
Name: StockOptionLevel, dtype: int64

In [9]:
data=data.drop(['HourlyRate','Over18','MonthlyRate','DailyRate','StandardHours','EmployeeCount'],axis=1)
data.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,1,2,Female,3,2,Sales Executive,4,Single,5993,8,Yes,11,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,2,3,Male,2,2,Research Scientist,2,Married,5130,1,No,23,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,4,Male,2,1,Laboratory Technician,3,Single,2090,6,Yes,15,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,5,4,Female,3,1,Research Scientist,3,Married,2909,1,Yes,11,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,7,1,Male,3,1,Laboratory Technician,2,Married,3468,9,No,12,3,4,1,6,3,3,2,2,2,2

In [10]:
data.DistanceFromHome.value_counts()

2     211
1     208
10     86
9      85
3      84
7      84
8      80
5      65
4      64
6      59
16     32
11     29
24     28
29     27
23     27
18     26
15     26
20     25
25     25
26     25
28     23
19     22
14     21
12     20
17     20
13     19
22     19
21     18
27     12
Name: DistanceFromHome, dtype: int64

In [11]:
#Defining a fxn to classify their distance from home
def distance (x):
    if x<=9:
        return 'Short Distance'
    elif x<=19:
        return 'Moderately Far'
    else:
        return 'Far'
data['Distance_score']=data['DistanceFromHome'].apply(distance)

In [12]:
data

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Distance_score
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,1,2,Female,3,2,Sales Executive,4,Single,5993,8,Yes,11,3,1,0,8,0,1,6,4,0,5,Short Distance
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,2,3,Male,2,2,Research Scientist,2,Married,5130,1,No,23,4,4,1,10,3,3,10,7,1,7,Short Distance
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,4,Male,2,1,Laboratory Technician,3,Single,2090,6,Yes,15,3,2,0,7,3,3,0,0,0,0,Short Distance
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,5,4,Female,3,1,Research Scientist,3,Married,2909,1,Yes,11,3,3,0,8,3,3,8,7,3,0,Short Distance
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,7,1,Male,3,1,Laboratory Technician,2,Married,3468,9,No,12,3,4,1,6,3,3,2,2,2,2,Short Distance
5,32,No,Travel_Frequently,Research & Development,2,2,Life Sciences,8,4,Male,3,1,Laboratory Technician,4,Single,3068,0,No,13,3,3,0,8,2,2,7,7,3,6,Short Distance
6,59,No,Travel_Rarely,Research & Development,3,3,Medical,10,3,Female,4,1,Laboratory Technician,1,Married,2670,4,Yes,20,4,1,3,12,3,2,1,0,0,0,Short Distance
7,30,No,Travel_Rarely,Research & Development,24,1,Life Sciences,11,4,Male,3,1,Laboratory Technician,3,Divorced,2693,1,No,22,4,2,1,1,2,3,1,0,0,0,Far
8,38,No,Travel_Frequently,Research & Development,23,3,Life Sciences,12,4,Male,2,3,Manufacturing Director,3,Single,9526,0,No,21,4,2,0,10,2,3,9,7,1,8,Far
9,36,No,Travel_Rarely,Research & Development,27,3,Medical,13,3,Male,3,2,Healthcare Representative,3,Married,5237,6,No,13,3,2,2,17,3,2,7,7,7,7,Far
10,35,No,Travel_Rarely,Research & Development,16,3,Medical,14,1,Male,4,1,Laboratory Technician,2,Married,2426,0,No,13,3,3,1,6,5,3,5,4,0,3,Moderately Far
11,29,No,Travel_Rarely,Research & Development,15,2,Life Sciences,15,4,Female,2,2,Laboratory Technician,3,Single,4193,0,Yes,12,3,4,0,10,3,3,9,5,0,8,Moderately Far
12,31,No,Travel_Rarely,Research & Development,26,1,Life Sciences,16,1,Male,3,1,Research Scientist,3,Divorced,2911,1,No,17,3,4,1,5,1,2,5,2,4,3,Far
13,34,No,Travel_Rarely,Research & Development,19,2,Medical,18,2,Male,3,1,Laboratory Technician,4,Divorced,2661,0,No,11,3,3,1,3,2,3,2,2,1,2,Moderately Far
14,28,Yes,Travel_Rarely,Research & Development,24,3,Life Sciences,19,3,Male,2,1,Laboratory Technician,3,Single,2028,5,Yes,14,3,2,0,6,4,3,4,2,0,3,Far
15,29,No,Travel_Rarely,Research & Development,21,4,Life Sciences,20,2,Female,4,3,Manufacturing Director,1,Divorced,9980,1,No,11,3,3,1,10,1,3,10,9,8,8,Far
16,32,No,Travel_Rarely,Research & Development,5,2,Life Sciences,21,1,Male,4,1,Research Scientist,2,Divorced,3298,0,Yes,12,3,4,2,7,5,2,6,2,0,5,Short Distance
17,22,No,Non-Travel,Research & Development,16,2,Medical,22,4,Male,4,1,Laboratory Technician,4,Divorced,2935,1,Yes,13,3,2,2,1,2,2,1,0,0,0,Moderately Far
18,53,No,Travel_Rarely,Sales,2,4,Life Sciences,23,1,Female,2,4,Manager,4,Married,15427,2,No,16,3,3,0,31,3,3,25,8,3,7,Short Distance
19,38,No,Travel_Rarely,Research & Development,2,3,Life Sciences,24,4,Male,3,1,Research Scientist,4,Single,3944,5,Yes,11,3,3,0,6,3,3,3,2,1,2,Short Distance
20,24,No,Non-Travel,Research & Development,11,2,Other,26,1,Female,4,2,Manufacturing Director,3,Divorced,4011,0,No,18,3,4,1,5,5,2,4,2,1,3,Moderately Far
21,36,Yes,Travel_Rarely,Sales,9,4,Life Sciences,27,3,Male,2,1,Sales Representative,1,Single,3407,7,No,23,4,2,0,10,4,3,5,3,0,3,Short Distance
22,34,No,Travel_Rarely,Research & Development,7,4,Life Sciences,28,1,Female,3,3,Research Director,2,Single,11994,0,No,11,3,3,0,13,4,3,12,6,2,11,Short Distance
23,21,No,Travel_Rarely,Research & Development,15,2,Life Sciences,30,3,Male,3,1,Research Scientist,4,Single,1232,1,No,14,3,4,0,0,6,3,0,0,0,0,Moderately Far
24,34,Yes,Travel_Rarely,Research & Development,6,1,Medical,31,2,Male,3,1,Research Scientist,1,Single,2960,2,No,11,3,3,0,8,2,3,4,2,1,3,Short Distance
25,53,No,Travel_Rarely,Research & Development,5,3,Other,32,3,Female,3,5,Manager,3,Divorced,19094,4,No,11,3,4,1,26,3,2,14,13,4,8,Short Distance
26,32,Yes,Travel_Frequently,Research & Development,16,1,Life Sciences,33,2,Female,1,1,Research Scientist,1,Single,3919,1,Yes,22,4,2,0,10,5,3,10,2,6,7,Moderately Far
27,42,No,Travel_Rarely,Sales,8,4,Marketing,35,3,Male,3,2,Sales Executive,2,Married,6825,0,No,11,3,4,1,10,2,3,9,7,4,2,Short Distance
28,44,No,Travel_Rarely,Research & Development,7,4,Medical,36,1,Female,2,3,Healthcare Representative,4,Married,10248,3,No,14,3,4,1,24,4,3,22,6,5,17,Short Distance
29,46,No,Travel_Rarely,Sales,2,4,Marketing,38,2,Female,3,5,Manager,1,Single,18947,3,No,12,3,4,0,22,2,2,2,2,2,1,Short Distance
30,33,No,Travel_Rarely,Research & Development,2,3,Medical,39,3,Male,3,1,Laboratory Technician,4,Single,2496,4,No,11,3,4,0,7,3,3,1,1,0,0,Short Distance
31,44,No,Travel_Rarely,Research & Development,10,4,Other,40,4,Male,3,2,Healthcare Representative,4,Married,6465,2,Yes,13,3,4,0,9,5,4,4,2,1,3,Moderately Far
32,30,No,Travel_Rarely,Research & Development,9,2,Medical,41,4,Male,2,1,Laboratory Technician,3,Single,2206,1,No,13,3,1,0,10,5,3,10,0,1,8,Short Distance
33,39,Yes,Travel_Rarely,Sales,5,3,Technical Degree,42,4,Male,3,2,Sales Representative,4,Married,2086,3,No,14,3,3,1,19,6,4,1,0,0,0,Short Distance
34,24,Yes,Travel_Rarely,Research & Development,1,3,Medical,45,2,Male,3,1,Research Scientist,4,Married,2293,2,Yes,16,3,1,1,6,2,2,2,0,2,0,Short Distance
35,43,No,Travel_Rarely,Research & Development,2,2,Medical,46,4,Female,4,1,Research Scientist,3,Divorced,2645,1,No,12,3,4,2,6,3,2,5,3,1,4,Short Distance
36,50,Yes,Travel_Rarely,Sales,3,2,Marketing,47,1,Male,2,1,Sales Representative,3,Married,2683,1,Yes,14,3,3,0,3,2,3,3,2,0,2,Short Distance
37,35,No,Travel_Rarely,Sales,2,3,Marketing,49,4,Female,3,1,Sales Representative,4,Married,2014,1,No,13,3,1,0,2,3,3,2,2,2,2,Short Distance
38,36,No,Travel_Rarely,Research & Development,5,4,Life Sciences,51,2,Female,2,1,Research Scientist,1,Married,3419,9,Yes,14,3,4,1,6,3,4,1,1,0,0,Short Distance
39,33,No,Travel_Frequently,Sales,1,3,Life Sciences,52,3,Female,4,2,Sales Executive,1,Married,5376,2,No,19,3,1,2,10,3,3,5,3,1,3,Short Distance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,38,No,Travel_Rarely,Research & Development,10,3,Medical,2015,2,Female,1,3,Research Director,3,Married,13206,3,No,12,3,1,1,20,3,3,18,16,1,11,Moderately Far
1431,32,No,Travel_Rarely,Sales,1,4,Marketing,2016,3,Female,3,3,Sales Executive,4,Married,10422,1,No,19,3,3,2,14,3,3,14,10,5,7,Short Distance
1432,37,No,Travel_Rarely,Research & Development,10,3,Life Sciences,2017,3,Female,4,3,Research Director,4,Married,13744,1,Yes,25,4,1,1,16,2,3,16,11,6,8,Moderately Far
1433,25,No,Travel_Rarely,Sales,8,2,Other,2018,1,Female,3,2,Sales Executive,3,Divorced,4907,0,Yes,22,4,2,1,6,3,2,5,3,0,4,Short Distance
1434,52,No,Non-Travel,Sales,29,4,Life Sciences,2019,1,Male,3,1,Sales Representative,4,Divorced,3482,2,No,15,3,2,2,16,3,2,9,8,0,0,Far
1435,44,No,Travel_Rarely,Research & Development,1,3,Medical,2020,2,Male,3,1,Research Scientist,4,Single,2436,6,Yes,12,3,3,0,6,2,3,4,3,1,2,Short Distance
1436,21,No,Travel_Rarely,Sales,5,1,Medical,2021,3,Male,3,1,Sales Representative,1,Single,2380,1,Yes,11,3,4,0,2,6,3,2,2,1,2,Short Distance
1437,39,No,Non-Travel,Research & Development,9,3,Life Sciences,2022,4,Male,3,5,Manager,4,Single,19431,2,No,13,3,3,0,21,3,2,6,0,1,3,Short Distance
1438,23,Yes,Travel_Frequently,Sales,9,3,Marketing,2023,4,Male,3,1,Sales Representative,1,Married,1790,1,No,19,3,1,1,1,3,2,1,0,1,0,Short Distance
1439,36,No,Travel_Rarely,Sales,3,3,Medical,2024,1,Female,2,3,Sales Executive,4,Married,7644,0,No,19,3,3,2,10,2,3,9,7,3,4,Short Distance
1440,36,No,Travel_Frequently,Research & Development,4,2,Life Sciences,2025,4,Female,3,2,Manufacturing Director,2,Divorced,5131,7,No,13,3,2,3,18,3,3,4,2,0,2,Short Distance
1441,56,No,Non-Travel,Research & Development,1,4,Life Sciences,2026,3,Male,3,2,Healthcare Representative,3,Divorced,6306,1,No,21,4,1,1,13,2,2,13,12,1,9,Short Distance
1442,29,Yes,Travel_Rarely,Research & Development,1,4,Medical,2027,1,Male,3,1,Research Scientist,4,Married,4787,9,Yes,14,3,2,3,4,3,4,2,2,2,2,Short Distance
1443,42,No,Travel_Rarely,Research & Development,2,3,Life Sciences,2031,1,Male,3,5,Manager,3,Married,18880,5,No,11,3,1,0,24,2,2,22,6,4,14,Short Distance
1444,56,Yes,Travel_Rarely,Research & Development,7,2,Technical Degree,2032,4,Male,3,1,Laboratory Technician,3,Married,2339,8,No,11,3,4,1,14,4,1,10,9,9,8,Short Distance
1445,41,No,Travel_Rarely,Research & Development,28,4,Life Sciences,2034,1,Female,2,4,Manufacturing Director,2,Married,13570,0,No,23,4,3,1,21,3,3,20,7,0,10,Far
1446,34,No,Travel_Rarely,Sales,28,3,Marketing,2035,4,Female,2,2,Sales Executive,3,Married,6712,1,No,21,4,4,2,8,2,3,8,7,1,7,Far
1447,36,No,Non-Travel,Sales,15,4,Marketing,2036,4,Male,1,2,Sales Executive,4,Divorced,5406,1,No,24,4,1,1,15,4,2,15,12,11,11,Moderately Far
1448,41,No,Travel_Rarely,Sales,3,3,Life Sciences,2037,3,Male,2,2,Sales Executive,2,Divorced,8938,2,No,11,3,3,1,14,5,3,5,4,0,4,Short Distance
1449,32,No,Travel_Rarely,Research & Development,2,3,Technical Degree,2038,4,Male,3,1,Research Scientist,1,Single,2439,1,No,14,3,4,0,4,4,3,4,2,1,2,Short Distance
1450,35,No,Travel_Rarely,Human Resources,26,4,Life Sciences,2040,3,Female,3,3,Human Resources,4,Single,8837,1,Yes,16,3,3,0,9,2,3,9,0,1,7,Far
1451,38,No,Travel_Rarely,Sales,10,2,Life Sciences,2041,1,Female,3,2,Sales Executive,4,Married,5343,1,No,11,3,3,1,10,1,3,10,7,1,9,Moderately Far
1452,50,Yes,Travel_Frequently,Sales,1,4,Life Sciences,2044,2,Male,3,2,Sales Executive,3,Divorced,6728,7,No,12,3,4,2,12,3,3,6,3,0,1,Short Distance
1453,36,No,Travel_Rarely,Sales,11,4,Marketing,2045,2,Female,2,2,Sales Executive,4,Married,6652,4,No,13,3,1,1,8,2,2,6,3,0,0,Moderately Far
1454,45,No,Travel_Rarely,Sales,20,3,Life Sciences,2046,4,Female,3,2,Sales Executive,3,Single,4850,8,No,15,3,3,0,8,3,3,5,3,0,1,Far
1455,40,No,Travel_Rarely,Research & Development,2,4,Life Sciences,2048,3,Male,2,1,Research Scientist,3,Single,2809,2,No,14,3,4,0,8,2,3,2,2,2,2,Short Distance
1456,35,No,Travel_Frequently,Research & Development,18,4,Life Sciences,2049,3,Male,3,2,Healthcare Representative,3,Married,5689,1,Yes,14,3,4,2,10,2,4,10,2,0,2,Moderately Far
1457,40,No,Travel_Rarely,Research & Development,2,4,Medical,2051,3,Female,3,1,Research Scientist,3,Married,2001,2,No,14,3,2,3,20,2,3,5,3,0,2,Short Distance
1458,35,No,Travel_Rarely,Research & Development,1,4,Life Sciences,2052,3,Female,1,1,Research Scientist,4,Married,2977,1,No,12,3,4,1,4,5,3,4,3,1,1,Short Distance
1459,29,No,Travel_Rarely,Research & Development,13,2,Other,2053,4,Male,2,2,Laboratory Technician,2,Married,4025,4,Yes,13,3,1,1,10,2,3,4,3,0,3,Moderately Far
1460,29,No,Travel_Rarely,Research & Development,28,4,Medical,2054,4,Female,2,1,Research Scientist,1,Single,3785,1,No,14,3,2,0,5,3,1,5,4,0,4,Far
1461,50,Yes,Travel_Rarely,Sales,28,3,Marketing,2055,4,Male,2,3,Sales Executive,1,Divorced,10854,4,Yes,13,3,2,1,20,3,3,3,2,2,0,Far
1462,39,No,Travel_Rarely,Sales,24,1,Marketing,2056,2,Female,2,4,Sales Executive,4,Married,12031,0,No,11,3,1,1,21,2,2,20,9,9,6,Far
1463,31,No,Non-Travel,Research & Development,5,3,Medical,2057,2,Male,3,2,Manufacturing Director,1,Single,9936,0,No,19,3,2,0,10,2,3,9,4,1,7,Short Distance
1464,26,No,Travel_Rarely,Sales,5,3,Other,2060,4,Female,2,1,Sales Representative,3,Single,2966,0,No,18,3,4,0,5,2,3,4,2,0,0,Short Distance
1465,36,No,Travel_Frequently,Research & Development,23,2,Medical,2061,3,Male,4,2,Laboratory Technician,4,Married,2571,4,No,17,3,3,1,17,3,3,5,2,0,3,Far
1466,39,No,Travel_Rarely,Research & Development,6,1,Medical,2062,4,Male,2,3,Healthcare Representative,1,Married,9991,4,No,15,3,1,1,9,5,3,7,7,1,7,Short Distance
1467,27,No,Travel_Rarely,Research & Development,4,3,Life Sciences,2064,2,Male,4,2,Manufacturing Director,2,Married,6142,1,Yes,20,4,2,1,6,0,3,6,2,0,3,Short Distance
1468,49,No,Travel_Frequently,Sales,2,3,Medical,2065,4,Male,2,2,Sales Executive,2,Married,5390,2,No,14,3,4,0,17,3,2,9,6,0,8,Short Distance
1469,34,No,Travel_Rarely,Research & Development,8,3,Medical,2068,2,Male,4,2,Laboratory Technician,3,Married,4404,2,No,12,3,1,0,6,3,4,4,3,1,2,Short Distance

In [13]:
data.Distance_score.value_counts()

Short Distance    940
Moderately Far    301
Far               229
Name: Distance_score, dtype: int64

In [14]:
distance=data['DistanceFromHome']
data=data.drop(['DistanceFromHome'],1)

In [15]:
data=data.drop(['EducationField'],1)

In [16]:
data.head()

,Age,Attrition,BusinessTravel,Department,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Distance_score
0,41,Yes,Travel_Rarely,Sales,2,1,2,Female,3,2,Sales Executive,4,Single,5993,8,Yes,11,3,1,0,8,0,1,6,4,0,5,Short Distance
1,49,No,Travel_Frequently,Research & Development,1,2,3,Male,2,2,Research Scientist,2,Married,5130,1,No,23,4,4,1,10,3,3,10,7,1,7,Short Distance
2,37,Yes,Travel_Rarely,Research & Development,2,4,4,Male,2,1,Laboratory Technician,3,Single,2090,6,Yes,15,3,2,0,7,3,3,0,0,0,0,Short Distance
3,33,No,Travel_Frequently,Research & Development,4,5,4,Female,3,1,Research Scientist,3,Married,2909,1,Yes,11,3,3,0,8,3,3,8,7,3,0,Short Distance
4,27,No,Travel_Rarely,Research & Development,1,7,1,Male,3,1,Laboratory Technician,2,Married,3468,9,No,12,3,4,1,6,3,3,2,2,2,2,Short Distance

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [18]:
data['Attrition']=le.fit_transform(data['Attrition'])

In [19]:
data['OverTime']=le.fit_transform(data['OverTime'])

In [20]:
data.Gender.value_counts()

Male      882
Female    588
Name: Gender, dtype: int64

In [21]:
data['Gender']=le.fit_transform(data['Gender'])
data.head()

,Age,Attrition,BusinessTravel,Department,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Distance_score
0,41,1,Travel_Rarely,Sales,2,1,2,0,3,2,Sales Executive,4,Single,5993,8,1,11,3,1,0,8,0,1,6,4,0,5,Short Distance
1,49,0,Travel_Frequently,Research & Development,1,2,3,1,2,2,Research Scientist,2,Married,5130,1,0,23,4,4,1,10,3,3,10,7,1,7,Short Distance
2,37,1,Travel_Rarely,Research & Development,2,4,4,1,2,1,Laboratory Technician,3,Single,2090,6,1,15,3,2,0,7,3,3,0,0,0,0,Short Distance
3,33,0,Travel_Frequently,Research & Development,4,5,4,0,3,1,Research Scientist,3,Married,2909,1,1,11,3,3,0,8,3,3,8,7,3,0,Short Distance
4,27,0,Travel_Rarely,Research & Development,1,7,1,1,3,1,Laboratory Technician,2,Married,3468,9,0,12,3,4,1,6,3,3,2,2,2,2,Short Distance

In [22]:
dataset=pd.get_dummies(data,columns=['Department','JobRole','MaritalStatus','BusinessTravel','Distance_score'])
dataset

,Age,Attrition,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Human Resources,Department_Research & Development,Department_Sales,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Distance_score_Far,Distance_score_Moderately Far,Distance_score_Short Distance
0,41,1,2,1,2,0,3,2,4,5993,8,1,11,3,1,0,8,0,1,6,4,0,5,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1
1,49,0,1,2,3,1,2,2,2,5130,1,0,23,4,4,1,10,3,3,10,7,1,7,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1
2,37,1,2,4,4,1,2,1,3,2090,6,1,15,3,2,0,7,3,3,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1
3,33,0,4,5,4,0,3,1,3,2909,1,1,11,3,3,0,8,3,3,8,7,3,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1
4,27,0,1,7,1,1,3,1,2,3468,9,0,12,3,4,1,6,3,3,2,2,2,2,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1
5,32,0,2,8,4,1,3,1,4,3068,0,0,13,3,3,0,8,2,2,7,7,3,6,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1
6,59,0,3,10,3,0,4,1,1,2670,4,1,20,4,1,3,12,3,2,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1
7,30,0,1,11,4,1,3,1,3,2693,1,0,22,4,2,1,1,2,3,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0
8,38,0,3,12,4,1,2,3,3,9526,0,0,21,4,2,0,10,2,3,9,7,1,8,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0
9,36,0,3,13,3,1,3,2,3,5237,6,0,13,3,2,2,17,3,2,7,7,7,7,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0
10,35,0,3,14,1,1,4,1,2,2426,0,0,13,3,3,1,6,5,3,5,4,0,3,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0
11,29,0,2,15,4,0,2,2,3,4193,0,1,12,3,4,0,10,3,3,9,5,0,8,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0
12,31,0,1,16,1,1,3,1,3,2911,1,0,17,3,4,1,5,1,2,5,2,4,3,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0
13,34,0,2,18,2,1,3,1,4,2661,0,0,11,3,3,1,3,2,3,2,2,1,2,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0
14,28,1,3,19,3,1,2,1,3,2028,5,1,14,3,2,0,6,4,3,4,2,0,3,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0
15,29,0,4,20,2,0,4,3,1,9980,1,0,11,3,3,1,10,1,3,10,9,8,8,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0
16,32,0,2,21,1,1,4,1,2,3298,0,1,12,3,4,2,7,5,2,6,2,0,5,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1
17,22,0,2,22,4,1,4,1,4,2935,1,1,13,3,2,2,1,2,2,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0
18,53,0,4,23,1,0,2,4,4,15427,2,0,16,3,3,0,31,3,3,25,8,3,7,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1
19,38,0,3,24,4,1,3,1,4,3944,5,1,11,3,3,0,6,3,3,3,2,1,2,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1
20,24,0,2,26,1,0,4,2,3,4011,0,0,18,3,4,1,5,5,2,4,2,1,3,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0
21,36,1,4,27,3,1,2,1,1,3407,7,0,23,4,2,0,10,4,3,5,3,0,3,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1
22,34,0,4,28,1,0,3,3,2,11994,0,0,11,3,3,0,13,4,3,12,6,2,11,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1
23,21,0,2,30,3,1,3,1,4,1232,1,0,14,3,4,0,0,6,3,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,1,0
24,34,1,1,31,2,1,3,1,1,2960,2,0,11,3,3,0,8,2,3,4,2,1,3,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1
25,53,0,3,32,3,0,3,5,3,19094,4,0,11,3,4,1,26,3,2,14,13,4,8,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1
26,32,1,1,33,2,0,1,1,1,3919,1,1,22,4,2,0,10,5,3,10,2,6,7,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1,0
27,42,0,4,35,3,1,3,2,2,6825,0,0,11,3,4,1,10,2,3,9,7,4,2,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1
28,44,0,4,36,1,0,2,3,4,10248,3,0,14,3,4,1,24,4,3,22,6,5,17,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1
29,46,0,4,38,2,0,3,5,1,18947,3,0,12,3,4,0,22,2,2,2,2,2,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1
30,33,0,3,39,3,1,3,1,4,2496,4,0,11,3,4,0,7,3,3,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1
31,44,0,4,40,4,1,3,2,4,6465,2,1,13,3,4,0,9,5,4,4,2,1,3,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0
32,30,0,2,41,4,1,2,1,3,2206,1,0,13,3,1,0,10,5,3,10,0,1,8,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1
33,39,1,3,42,4,1,3,2,4,2086,3,0,14,3,3,1,19,6,4,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1
34,24,1,3,45,2,1,3,1,4,2293,2,1,16,3,1,1,6,2,2,2,0,2,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1
35,43,0,2,46,4,0,4,1,3,2645,1,0,12,3,4,2,6,3,2,5,3,1,4,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1
36,50,1,2,47,1,1,2,1,3,2683,1,1,14,3,3,0,3,2,3,3,2,0,2,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1
37,35,0,3,49,4,0,3,1,4,2014,1,0,13,3,1,0,2,3,3,2,2,2,2,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,1
38,36,0,4,51,2,0,2,1,1,3419,9,1,14,3,4,1,6,3,4,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1
39,33,0,3,52,3,0,4,2,1,5376,2,0,19,3,1,2,10,3,3,5,3,1,3,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,38,0,3,2015,2,0,1,3,3,13206,3,0,12,3,1,1,20,3,3,18,16,1,11,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0
1431,32,0,4,2016,3,0,3,3,4,10422,1,0,19,3,3,2,14,3,3,14,10,5,7,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1
1432,37,0,3,2017,3,0,4,3,4,13744,1,1,25,4,1,1,16,2,3,16,11,6,8,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0
1433,25,0,2,2018,1,0,3,2,3,4907,0,1,22,4,2,1,6,3,2,5,3,0,4,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,1
1434,52,0,4,2019,1,1,3,1,4,3482,2,0,15,3,2,2,16,3,2,9,8,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,0,0
1435,44,0,3,2020,2,1,3,1,4,2436,6,1,12,3,3,0,6,2,3,4,3,1,2,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1
1436,21,0,1,2021,3,1,3,1,1,2380,1,1,11,3,4,0,2,6,3,2,2,1,2,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1
1437,39,0,3,2022,4,1,3,5,4,19431,2,0,13,3,3,0,21,3,2,6,0,1,3,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,1
1438,23,1,3,2023,4,1,3,1,1,1790,1,0,19,3,1,1,1,3,2,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,1
1439,36,0,3,2024,1,0,2,3,4,7644,0,0,19,3,3,2,10,2,3,9,7,3,4,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,1
1440,36,0,2,2025,4,0,3,2,2,5131,7,0,13,3,2,3,18,3,3,4,2,0,2,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1
1441,56,0,4,2026,3,1,3,2,3,6306,1,0,21,4,1,1,13,2,2,13,12,1,9,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1
1442,29,1,4,2027,1,1,3,1,4,4787,9,1,14,3,2,3,4,3,4,2,2,2,2,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1
1443,42,0,3,2031,1,1,3,5,3,18880,5,0,11,3,1,0,24,2,2,22,6,4,14,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1
1444,56,1,2,2032,4,1,3,1,3,2339,8,0,11,3,4,1,14,4,1,10,9,9,8,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1
1445,41,0,4,2034,1,0,2,4,2,13570,0,0,23,4,3,1,21,3,3,20,7,0,10,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0
1446,34,0,3,2035,4,0,2,2,3,6712,1,0,21,4,4,2,8,2,3,8,7,1,7,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,1,0,0
1447,36,0,4,2036,4,1,1,2,4,5406,1,0,24,4,1,1,15,4,2,15,12,11,11,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,1,0
1448,41,0,3,2037,3,1,2,2,2,8938,2,0,11,3,3,1,14,5,3,5,4,0,4,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,1
1449,32,0,3,2038,4,1,3,1,1,2439,1,0,14,3,4,0,4,4,3,4,2,1,2,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1
1450,35,0,4,2040,3,0,3,3,4,8837,1,1,16,3,3,0,9,2,3,9,0,1,7,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0
1451,38,0,2,2041,1,0,3,2,4,5343,1,0,11,3,3,1,10,1,3,10,7,1,9,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0
1452,50,1,4,2044,2,1,3,2,3,6728,7,0,12,3,4,2,12,3,3,6,3,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1
1453,36,0,4,2045,2,0,2,2,4,6652,4,0,13,3,1,1,8,2,2,6,3,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0
1454,45,0,3,2046,4,0,3,2,3,4850,8,0,15,3,3,0,8,3,3,5,3,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0
1455,40,0,4,2048,3,1,2,1,3,2809,2,0,14,3,4,0,8,2,3,2,2,2,2,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1
1456,35,0,4,2049,3,1,3,2,3,5689,1,1,14,3,4,2,10,2,4,10,2,0,2,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0
1457,40,0,4,2051,3,0,3,1,3,2001,2,0,14,3,2,3,20,2,3,5,3,0,2,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1
1458,35,0,4,2052,3,0,1,1,4,2977,1,0,12,3,4,1,4,5,3,4,3,1,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1
1459,29,0,2,2053,4,1,2,2,2,4025,4,1,13,3,1,1,10,2,3,4,3,0,3,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0
1460,29,0,4,2054,4,0,2,1,1,3785,1,0,14,3,2,0,5,3,1,5,4,0,4,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0
1461,50,1,3,2055,4,1,2,3,1,10854,4,1,13,3,2,1,20,3,3,3,2,2,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,1,0,0
1462,39,0,1,2056,2,0,2,4,4,12031,0,0,11,3,1,1,21,2,2,20,9,9,6,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,1,0,0
1463,31,0,3,2057,2,1,3,2,1,9936,0,0,19,3,2,0,10,2,3,9,4,1,7,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,1
1464,26,0,3,2060,4,0,2,1,3,2966,0,0,18,3,4,0,5,2,3,4,2,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,1
1465,36,0,2,2061,3,1,4,2,4,2571,4,0,17,3,3,1,17,3,3,5,2,0,3,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0
1466,39,0,1,2062,4,1,2,3,1,9991,4,0,15,3,1,1,9,5,3,7,7,1,7,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1
1467,27,0,3,2064,2,1,4,2,2,6142,1,1,20,4,2,1,6,0,3,6,2,0,3,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1
1468,49,0,3,2065,4,1,2,2,2,5390,2,0,14,3,4,0,17,3,2,9,6,0,8,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1
1469,34,0,3,2068,2,1,4,2,3,4404,2,0,12,3,1,0,6,3,4,4,3,1,2,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1

In [23]:
dataset=dataset.drop(['Department_Human Resources','JobRole_Healthcare Representative','MaritalStatus_Divorced','BusinessTravel_Non-Travel','Distance_score_Far'],1)
dataset.head()

,Age,Attrition,Education,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Research & Development,Department_Sales,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Distance_score_Moderately Far,Distance_score_Short Distance
0,41,1,2,1,2,0,3,2,4,5993,8,1,11,3,1,0,8,0,1,6,4,0,5,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,1
1,49,0,1,2,3,1,2,2,2,5130,1,0,23,4,4,1,10,3,3,10,7,1,7,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,1
2,37,1,2,4,4,1,2,1,3,2090,6,1,15,3,2,0,7,3,3,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1
3,33,0,4,5,4,0,3,1,3,2909,1,1,11,3,3,0,8,3,3,8,7,3,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,1
4,27,0,1,7,1,1,3,1,2,3468,9,0,12,3,4,1,6,3,3,2,2,2,2,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1

In [24]:
EmployeeNumber=dataset['EmployeeNumber']

In [25]:
x=dataset.drop(['Attrition','EmployeeNumber'],1)
y=dataset['Attrition']

In [33]:
y

0       1
1       0
2       1
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      1
15      0
16      0
17      0
18      0
19      0
20      0
21      1
22      0
23      0
24      1
25      0
26      1
27      0
28      0
29      0
30      0
31      0
32      0
33      1
34      1
35      0
36      1
37      0
38      0
39      0
       ..
1430    0
1431    0
1432    0
1433    0
1434    0
1435    0
1436    0
1437    0
1438    1
1439    0
1440    0
1441    0
1442    1
1443    0
1444    1
1445    0
1446    0
1447    0
1448    0
1449    0
1450    0
1451    0
1452    1
1453    0
1454    0
1455    0
1456    0
1457    0
1458    0
1459    0
1460    0
1461    1
1462    0
1463    0
1464    0
1465    0
1466    0
1467    0
1468    0
1469    0
Name: Attrition, Length: 1470, dtype: int32

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3, random_state=0)

In [35]:
x_train.head()

,Age,Education,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Research & Development,Department_Sales,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Distance_score_Moderately Far,Distance_score_Short Distance
822,34,2,4,1,3,2,3,4033,2,0,11,3,4,0,5,3,2,3,2,0,2,1,0,0,0,0,1,0,0,0,0,0,1,1,0,0,1
655,33,2,4,1,3,1,2,2277,3,1,11,3,3,1,7,4,4,4,3,0,3,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1
517,25,3,4,1,4,2,2,4851,0,0,22,4,3,1,4,4,3,3,2,1,2,0,1,0,0,0,0,0,0,1,0,1,0,0,1,0,1
1346,45,2,2,0,2,2,4,5906,0,0,13,3,4,2,10,2,2,9,8,3,8,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0
1457,40,4,3,0,3,1,3,2001,2,0,14,3,2,3,20,2,3,5,3,0,2,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,1

In [36]:
y_train.head()

822     0
655     0
517     0
1346    0
1457    0
Name: Attrition, dtype: int32

In [37]:
y_test.head()

442     0
1091    0
981     1
785     0
1332    1
Name: Attrition, dtype: int32

In [38]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
X_train=mms.fit_transform(x_train)
X_test=mms.transform(x_test)

In [39]:
X_train

array([[0.38095238, 0.25      , 1.        , ..., 0.        , 0.        ,
        1.        ],
       [0.35714286, 0.25      , 1.        , ..., 1.        , 0.        ,
        1.        ],
       [0.16666667, 0.5       , 1.        , ..., 1.        , 0.        ,
        1.        ],
       ...,
       [0.5952381 , 0.5       , 1.        , ..., 1.        , 0.        ,
        1.        ],
       [0.47619048, 1.        , 1.        , ..., 1.        , 0.        ,
        1.        ],
       [0.52380952, 0.75      , 0.        , ..., 1.        , 1.        ,
        0.        ]])

In [40]:
x_train.columns

Index(['Age', 'Education', 'EnvironmentSatisfaction', 'Gender',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Department_Research & Development',
       'Department_Sales', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'BusinessTravel_Travel_Frequently',
       'BusinessTravel_Travel_Rarely', 'Distance_score_Moderately Far',
       'Distance_score_Short Distance'],
      dtype='object')

In [41]:
Columns=['Age', 'Education', 'EnvironmentSatisfaction', 'Gender',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Department_Research & Development',
       'Department_Sales', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'BusinessTravel_Travel_Frequently',
       'BusinessTravel_Travel_Rarely', 'Distance_score_Moderately Far',
       'Distance_score_Short_Distance']

In [42]:
X1_train=pd.DataFrame(data=X_train,columns=Columns)
X1_train

,Age,Education,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Research & Development,Department_Sales,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Distance_score_Moderately Far,Distance_score_Short_Distance
0,0.380952,0.25,1.000000,1.0,0.666667,0.25,0.666667,0.159242,0.222222,0.0,0.000000,0.0,1.000000,0.000000,0.125,0.500000,0.333333,0.075,0.111111,0.000000,0.117647,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,0.357143,0.25,1.000000,1.0,0.666667,0.00,0.333333,0.066772,0.333333,1.0,0.000000,0.0,0.666667,0.333333,0.175,0.666667,1.000000,0.100,0.166667,0.000000,0.176471,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
2,0.166667,0.50,1.000000,1.0,1.000000,0.25,0.333333,0.202317,0.000000,0.0,0.785714,1.0,0.666667,0.333333,0.100,0.666667,0.666667,0.075,0.111111,0.066667,0.117647,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,0.642857,0.25,0.333333,0.0,0.333333,0.25,1.000000,0.257873,0.000000,0.0,0.142857,0.0,1.000000,0.666667,0.250,0.333333,0.333333,0.225,0.444444,0.200000,0.470588,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.523810,0.75,0.666667,0.0,0.666667,0.00,0.666667,0.052238,0.222222,0.0,0.214286,0.0,0.333333,1.000000,0.500,0.333333,0.666667,0.125,0.166667,0.000000,0.117647,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
5,0.047619,0.00,1.000000,1.0,0.666667,0.00,0.666667,0.000000,0.111111,1.0,0.000000,0.0,1.000000,0.000000,0.025,0.833333,0.666667,0.025,0.000000,0.066667,0.058824,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
6,0.214286,0.00,0.333333,1.0,0.666667,0.00,0.000000,0.057399,0.000000,0.0,0.214286,0.0,0.333333,0.000000,0.150,0.500000,1.000000,0.125,0.000000,0.066667,0.235294,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
7,0.452381,0.75,0.333333,0.0,0.666667,0.25,0.333333,0.286361,0.666667,0.0,0.071429,0.0,0.333333,0.333333,0.200,0.333333,0.333333,0.150,0.277778,0.266667,0.176471,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
8,0.476190,0.50,1.000000,1.0,0.666667,0.25,1.000000,0.196209,0.777778,0.0,0.285714,0.0,1.000000,0.666667,0.475,0.666667,1.000000,0.325,0.611111,0.133333,0.529412,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
9,0.761905,0.50,0.666667,0.0,0.666667,0.50,1.000000,0.431754,0.444444,0.0,0.000000,0.0,1.000000,0.000000,0.400,0.500000,0.666667,0.050,0.111111,0.133333,0.058824,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
10,0.261905,0.75,0.333333,0.0,1.000000,0.50,0.000000,0.472407,0.111111,0.0,0.000000,0.0,0.666667,0.333333,0.250,0.166667,0.666667,0.250,0.500000,0.533333,0.470588,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11,0.142857,0.25,1.000000,0.0,0.666667,0.00,0.333333,0.063244,0.111111,0.0,0.142857,0.0,0.000000,0.333333,0.025,0.500000,0.000000,0.025,0.000000,0.000000,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
12,0.238095,0.50,0.666667,1.0,0.333333,0.25,0.000000,0.195629,0.111111,0.0,0.000000,0.0,0.666667,0.333333,0.125,0.000000,0.666667,0.125,0.166667,0.000000,0.235294,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
13,0.357143,0.00,0.333333,1.0,0.666667,0.50,0.666667,0.663560,0.777778,1.0,0.071429,0.0,1.000000,0.000000,0.375,0.333333,1.000000,0.175,0.333333,0.466667,0.411765,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
14,0.214286,0.50,0.000000,0.0,0.333333,0.00,0.333333,0.097630,0.111111,0.0,0.071429,0.0,0.000000,0.000000,0.025,0.333333,0.666667,0.025,0.000000,0.000000,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
15,0.142857,0.25,1.000000,1.0,0.333333,0.00,0.333333,0.058873,0.111111,0.0,0.714286,1.0,1.000000,0.333333,0.025,0.333333,0.666667,0.025,0.000000,0.000000,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
16,0.261905,0.50,1.000000,0.0,0.333333,0.00,0.000000,0.057925,0.111111,0.0,0.142857,0.0,0.666667,0.333333,0.025,0.333333,0.666667,0.025,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
17,0.547619,1.00,0.333333,0.0,0.666667,0.75,0.000000,0.820748,0.777778,0.0,0.357143,0.0,0.333333,0.333333,0.550,0.333333,0.666667,0.450,0.888889,0.733333,0.470588,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
18,0.380952,0.50,0.666667,0.0,0.666667,0.25,0.333333,0.180885,0.444444,0.0,0.142857,0.0,0.666667,0.666667,0.375,0.333333,1.000000,0.275,0.444444,0.333333,0.588235,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19,0.380952,0.50,0.000000,1.0,0.666667,0.50,1.000000,0.467562,0.111111,0.0,0.714286,1.0,0.000000,0.000000,0.350,0.500000,0.333333,0.350,0.444444,0.133333,0.058824,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
20,0.261905,0.25,1.000000,1.0,0.333333,0.25,0.333333,0.158820,0.444444,1.0,0.142857,0.0,0.000000,0.333333,0.250,0.333333,0.666667,0.100,0.166667,0.000000,0.176471,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
21,0.547619,0.00,0.333333,0.0,0.000000,1.00,0.666667,0.998631,0.111111,0.0,0.785714,1.0,0.333333,0.666667,0.525,0.500000,0.666667,0.525,0.888889,0.333333,0.588235,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
22,0.523810,0.50,0.666667,0.0,0.666667,0.25,1.000000,0.289837,0.444444,0.0,0.428571,0.0,1.000000,0.333333,0.300,0.500000,0.666667,0.125,0.166667,0.000000,0.176471,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
23,0.190476,0.25,0.000000,1.0,0.333333,0.00,0.000000,0.155134,0.111111,0.0,0.357143,0.0,0.000000,0.666667,0.150,0.333333,0.666667,0.125,0.166667,0.066667,0.176471,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
24,0.333333,0.50,0.000000,1.0,0.666667,0.00,0.666667,0.127646,0.666667,0.0,0.142857,0.0,0.000000,0.333333,0.250,0.500000,0.333333,0.125,0.111111,0.066667,0.176471,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
25,0.380952,0.75,0.000000,0.0,0.666667,0.25,0.666667,0.200105,0.111111,0.0,0.214286,0.0,0.666667,0.000000,0.400,0.500000,0.666667,0.400,0.722222,0.133333,0.588235,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
26,0.333333,0.50,0.000000,1.0,0.666667,0.25,1.000000,0.271353,0.111111,1.0,0.785714,1.0,0.333333,0.333333,0.225,0.500000,0.666667,0.225,0.444444,0.466667,0.470588,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
27,0.119048,0.50,1.000000,1.0,1.000000,0.00,0.666667,0.056029,0.222222,0.0,0.357143,0.0,1.000000,0.333333,0.100,0.333333,0.666667,0.050,0.111111,0.133333,0.117647,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
28,0.380952,0.25,0.333333,1.0,0.666667,0.00,0.666667,0.068404,0.000000,1.0,1.000000,1.0,0.333333,0.333333,0.300,0.666667,0.666667,0.275,0.555556,0.333333,0.411765,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0
29,0.761905,0.50,0.666667,0.0,0.666667,1.00,0.333333,0.996156,0.333333,0.0,0.285714,0.0,0.333333,0.000000,0.525,0.833333,0.666667,0.125,0.222222,0.266667,0.235294,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
30,0.428571,0.75,1.000000,0.0,0.333333,0.25,0.666667,0.177199,0.000000,0.0,0.285714,0.0,0.666667,0.000000,0.100,1.000000,0.666667,0.075,0.111111,0.066667,0.117647,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
31,0.761905,0.50,1.000000,1.0,0.666667,0.75,0.666667,0.682675,0.333333,1.0,0.500000,0.0,1.000000,0.333333,0.550,0.333333,0.666667,0.300,0.611111,0.066667,0.294118,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
32,0.261905,0.50,1.000000,1.0,0.666667,0.25,0.666667,0.191680,0.111111,0.0,0.214286,0.0,0.000000,0.333333,0.100,0.500000,0.333333,0.100,0.166667,0.000000,0.117647,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
33,0.357143,0.50,1.000000,0.0,0.666667,0.00,0.333333,0.091996,0.111111,0.0,0.142857,0.0,1.000000,0.333333,0.200,0.833333,0.666667,0.200,0.388889,0.066667,0.352941,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
34,0.452381,0.50,0.333333,0.0,0.666667,0.00,0.333333,0.154134,0.111111,0.0,0.000000,0.0,0.000000,0.333333,0.200,0.333333,0.000000,0.200,0.222222,0.466667,0.411765,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
35,0.261905,0.50,1.000000,1.0,0.666667,0.00,1.000000,0.062770,1.000000,0.0,0.357143,0.0,1.000000,0.000000,0.150,0.666667,0.666667,0.075,0.111111,0.066667,0.117647,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
36,0.428571,0.25,0.333333,0.0,0.666667,0.50,1.000000,0.459663,0.000000,0.0,0.214286,0.0,0.666667,0.333333,0.250,1.000000,0.666667,0.225,0.388889,0.133333,0.470588,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
37,0.333333,0.75,1.000000,1.0,0.666667,0.25,1.000000,0.191627,0.888889,0.0,0.142857,0.0,0.666667,0.000000,0.100,0.333333,1.000000,0.000,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
38,0.261905,0.50,0.666667,1.0,0.666667,0.00,1.000000,0.070090,0.111111,0.0,0.571429,0.0,0.000000,0.000000,0.150,0.166667,0.666667,0.150,0.277778,0.066667,0.294118,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
39,0.428571,0.75,0.666667,0.0,0.666667,0.25,0.333333,0.231754,1.000000,1.0,0.000000,0.0,1.000000,0.000000,0.450,0.333333,0.666667,0.400,0.777778,0.333333,0.705882,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,0.690476,0.50,1.000000,0.0,0.666667,0.75,0.666667,0.671985,1.000000,1.0,0.071429,0.0,1.000000,0.666667,0.700,0.333333,0.333333,0.550,0.111111,0.733333,0.764706,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
941,0.738095,0.50,0.666667,0.0,0.666667,0.00,0.000000,0.135387,0.222222,0.0,0.357143,0.0,0.333333,0.333333,0.175,0.333333,0.666667,0.100,0.111111,0.000000,0.117647,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
942,0.261905,0.50,0.666667,0.0,0.666667,0.00,1.000000,0.060453,0.111111,0.0,0.285714,0.0,0.333333,0.333333,0.075,0.833333,0.666667,0.075,0.055556,0.000000,0.117647,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
943,0.476190,0.50,0.000000,1.0,0.666667,0.00,0.333333,0.083360,0.555556,0.0,0.142857,0.0,1.000000,1.000000,0.325,0.500000,0.666667,0.275,0.555556,0.200000,0.470588,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
944,0.309524,1.00,1.000000,1.0,1.000000,0.00,0.000000,0.102528,0.000000,0.0,0.428571,0.0,0.666667,0.000000,0.050,0.666667,0.666667,0.025,0.000000,0.000000,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
945,0.285714,0.75,0.666667,0.0,0.666667,0.50,0.000000,0.389837,0.000000,0.0,0.000000,0.0,0.666667,0.000000,0.250,0.500000,0.666667,0.225,0.444444,0.466667,0.470588,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
946,0.119048,0.25,1.000000,1.0,0.666667,0.00,0.666667,0.011269,0.111111,0.0,0.785714,1.0,1.000000,0.333333,0.025,0.333333,0.666667,0.025,0.000000,0.000000,0.058824,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
947,0.523810,0.50,0.000000,1.0,0.666667,0.00,0.000000,0.060927,0.333333,1.0,0.214286,0.0,0.333333,0.000000,0.250,0.500000,0.000000,0.100,0.111111,0.000000,0.176471,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
948,0.238095,0.75,0.000000,1.0,0.666667,0.25,1.000000,0.205319,0.111111,0.0,0.214286,0.0,0.333333,0.000000,0.100,0.500000,0.666667,0.100,0.111111,0.000000,0.117647,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
949,0.190476,0.50,0.000000,1.0,0.666667,0.00,0.666667,0.072038,0.111111,0.0,0.642857,1.0,0.666667,0.333333,0.025,0.000000,0.333333,0.025,0.055556,0.000000,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
950,0.547619,0.75,0.000000,0.0,0.333333,0.75,0.333333,0.661453,0.000000,0.0,0.857143,1.0,0.666667,0.333333,0.525,0.500000,0.666667,0.500,0.388889,0.000000,0.588235,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
951,0.119048,0.00,1.000000,1.0,0.333333,0.00,0.666667,0.156925,0.111111,1.0,0.000000,0.0,0.000000,0.000000,0.125,0.333333,0.666667,0.125,0.222222,0.066667,0.117647,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
952,0.619048,0.50,0.333333,1.0,0.666667,0.25,0.333333,0.054397,0.444444,0.0,0.071429,0.0,0.666667,0.333333,0.425,0.500000,1.000000,0.075,0.111111,0.066667,0.117647,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
953,0.333333,0.00,0.666667,0.0,0.666667,0.00,0.000000,0.095735,0.111111,0.0,0.071429,0.0,0.666667,1.000000,0.025,0.500000,0.666667,0.025,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
954,0.523810,0.50,0.333333,0.0,0.666667,0.75,0.666667,0.643918,0.777778,0.0,0.285714,0.0,0.666667,0.000000,0.550,0.500000,0.666667,0.500,0.333333,0.333333,0.764706,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
955,0.642857,0.25,1.000000,0.0,0.666667,0.75,1.000000,0.876303,0.333333,0.0,0.142857,0.0,0.333333,0.333333,0.650,0.666667,1.000000,0.225,0.166667,0.066667,0.058824,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
956,0.904762,0.50,1.000000,1.0,0.666667,0.75,0.333333,0.652607,0.444444,1.0,0.071429,0.0,0.000000,0.333333,0.825,0.000000,0.666667,0.475,0.888889,1.000000,0.529412,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
957,0.452381,0.50,0.666667,1.0,0.666667,0.50,1.000000,0.338020,0.222222,0.0,0.071429,0.0,0.000000,0.000000,0.300,0.500000,0.666667,0.125,0.166667,0.066667,0.176471,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
958,0.071429,0.50,0.666667,0.0,0.333333,0.00,0.000000,0.021432,0.111111,0.0,0.142857,0.0,0.000000,0.000000,0.025,1.000000,0.333333,0.025,0.000000,0.066667,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
959,0.309524,0.75,0.666667,1.0,0.666667,0.00,0.333333,0.078568,0.111111,0.0,0.428571,0.0,0.333333,0.000000,0.025,0.666667,0.666667,0.025,0.055556,0.066667,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
960,0.523810,0.25,0.666667,0.0,0.333333,0.25,1.000000,0.179726,0.333333,1.0,0.142857,0.0,1.000000,0.333333,0.400,0.500000,0.000000,0.025,0.055556,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
961,0.214286,0.25,1.000000,1.0,0.666667,0.50,0.000000,0.409900,0.111111,0.0,0.714286,1.0,0.666667,0.666667,0.225,0.666667,0.333333,0.225,0.388889,0.066667,0.411765,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
962,0.595238,0.50,0.000000,0.0,0.000000,0.25,0.666667,0.228383,0.888889,0.0,0.142857,0.0,0.333333,0.000000,0.175,0.333333,0.333333,0.100,0.166667,0.066667,0.176471,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
963,0.642857,0.25,0.666667,0.0,0.666667,0.25,0.000000,0.210479,0.444444,1.0,0.000000,0.0,0.000000,0.333333,0.225,0.500000,1.000000,0.125,0.222222,0.000000,0.176471,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
964,0.785714,0.75,1.000000,1.0,0.666667,0.00,1.000000,0.056135,0.333333,0.0,0.857143,1.0,0.333333,0.666667,0.250,0.666667,0.666667,0.100,0.111111,0.000000,0.176471,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
965,0.500000,0.50,0.666667,0.0,1.000000,0.25,0.333333,0.283307,1.000000,0.0,0.285714,0.0,0.666667,0.333333,0.300,0.500000,0.000000,0.200,0.166667,0.200000,0.352941,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
966,0.500000,1.00,0.000000,1.0,1.000000,0.50,0.666667,0.361822,0.000000,0.0,0.500000,0.0,1.000000,0.000000,0.225,0.500000,0.666667,0.200,0.388889,0.000000,0.411765,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
967,0.500000,0.00,0.666667,1.0,0.666667,0.75,0.000000,0.845656,0.111111,1.0,0.214286,0.0,1.000000,0.000000,0.525,0.500000,0.666667,0.525,0.500000,0.733333,0.588235,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
968,0.547619,0.50,1.000000,1.0,0.666667,0.00,1.000000,0.093365,0.333333,0.0,0.785714,1.0,0.000000,0.333333,0.300,0.500000,0.666667,0.125,0.166667,0.066667,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
969,0.333333,0.50,0.666667,0.0,0.333333,0.25,0.666667,0.271353,0.111111,0.0,0.071429,0.0,0.666667,0.333333,0.350,0.500000,0.666667,0.350,0.722222,0.400000,0.470588,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
970,0.523810,0.25,0.000000,1.0,0.666667,0.25,0.000000,0.235071,0.000000,0.0,0.071429,0.0,1.000000,0.000000,0.225,0.833333,1.000000,0.200,0.222222,0.466667,0.058824,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
971,0.428571,0.50,0.666667,1.0,0.666667,0.00,0.333333,0.059716,0.444444,0.0,0.142857,0.0,0.333333,0.333333,0.200,0.333333,0.666667,0.125,0.111111,0.000000,0.235294,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
972,0.476190,0.25,0.000000,0.0,1.000000,0.25,0.000000,0.242022,0.111111,1.0,0.928571,1.0,0.666667,0.333333,0.200,0.500000,0.666667,0.200,0.000000,0.466667,0.411765,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
973,0.309524,1.00,0.666667,0.0,1.000000,0.50,0.333333,0.338968,0.111111,0.0,0.000000,0.0,0.000000,0.000000,0.250,0.333333,0.666667,0.250,0.444444,0.266667,0.411765,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
974,0.428571,0.75,0.000000,1.0,1.000000,0.00,0.333333,0.094839,0.111111,0.0,0.785714,1.0,0.333333,0.000000,0.125,0.500000,0.666667,0.125,0.222222,0.000000,0.117647,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
975,0.380952,0.75,0.666667,0.0,0.666667,0.00,0.666667,0.063770,0.111111,1.0,0.571429,0.0,1.000000,0.333333,0.025,0.333333,0.666667,0.025,0.055556,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
976,0.404762,0.75,0.666667,1.0,0.666667,0.00,0.666667,0.174513,0.111111,0.0,0.428571,0.0,0.333333,0.000000,0.150,0.333333,0.000000,0.125,0.222222,0.066667,0.235294,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
977,0.595238,0.50,1.000000,1.0,0.666667,0.25,1.000000,0.360084,0.111111,1.0,0.428571,0.0,0.000000,0.333333,0.250,0.500000,0.666667,0.250,0.500000,0.533333,0.470588,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
978,0.476190,1.00,1.000000,1.0,0.666667,0.00,0.666667,0.107846,0.666667,1.0,0.142857,0.0,0.333333,0.333333,0.150,0.000000,0.000000,0.025,0.000000,0.000000,0.058824,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
979,0.523810,0.75,0.000000,1.0,0.333333,0.50,0.333333,0.457925,0.222222,0.0,0.071429,0.0,0.333333,0.333333,0.275,0.333333,0.333333,0.025,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [43]:
X1_test=pd.DataFrame(X_test,columns=Columns)
X1_test

,Age,Education,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Department_Research & Development,Department_Sales,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Distance_score_Moderately Far,Distance_score_Short_Distance
0,0.428571,0.75,0.333333,1.0,0.666667,0.50,1.000000,0.472407,0.111111,0.0,0.214286,0.0,1.000000,0.000000,0.250,0.500000,0.333333,0.250,0.166667,0.600000,0.411765,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.357143,0.50,1.000000,1.0,0.333333,0.25,0.333333,0.174355,0.111111,0.0,0.142857,0.0,1.000000,0.000000,0.125,0.333333,0.666667,0.125,0.166667,0.000000,0.117647,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,0.404762,0.75,1.000000,0.0,0.666667,0.25,0.666667,0.189837,0.000000,1.0,0.500000,0.0,0.666667,0.333333,0.125,0.000000,0.333333,0.100,0.111111,0.200000,0.117647,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
3,0.523810,0.75,0.000000,1.0,0.666667,0.50,1.000000,0.490416,0.444444,0.0,0.642857,1.0,1.000000,0.333333,0.350,1.000000,0.666667,0.275,0.555556,0.733333,0.058824,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.261905,0.25,1.000000,1.0,0.333333,0.00,1.000000,0.075303,0.111111,1.0,0.928571,1.0,0.333333,0.000000,0.025,0.500000,0.333333,0.025,0.000000,0.066667,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
5,0.285714,0.50,0.666667,0.0,0.666667,0.00,0.666667,0.056556,0.111111,0.0,0.642857,1.0,0.666667,0.333333,0.025,0.333333,0.666667,0.025,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
6,0.380952,0.75,0.000000,0.0,0.333333,0.25,0.333333,0.189047,0.000000,1.0,0.857143,1.0,0.666667,0.000000,0.400,0.333333,1.000000,0.375,0.500000,0.666667,0.588235,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
7,0.357143,0.50,1.000000,0.0,0.666667,0.25,0.333333,0.217904,0.888889,0.0,0.285714,0.0,1.000000,0.000000,0.325,0.333333,0.333333,0.275,0.388889,0.066667,0.411765,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
8,0.761905,0.50,1.000000,0.0,0.666667,0.25,0.666667,0.281095,0.000000,0.0,0.071429,0.0,0.000000,0.333333,0.475,0.500000,0.666667,0.450,0.388889,0.000000,0.764706,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
9,0.904762,0.75,0.333333,0.0,0.666667,0.00,0.333333,0.208215,1.000000,1.0,0.500000,0.0,0.000000,1.000000,0.175,0.333333,0.666667,0.125,0.222222,0.266667,0.176471,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
10,0.642857,0.25,0.666667,1.0,0.666667,0.75,1.000000,0.657557,0.000000,1.0,0.214286,0.0,0.333333,0.000000,0.525,0.333333,0.666667,0.500,0.388889,0.266667,0.588235,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
11,0.500000,0.50,0.666667,1.0,0.666667,0.00,0.000000,0.152449,0.000000,0.0,0.142857,0.0,0.000000,0.000000,0.150,0.333333,0.666667,0.125,0.111111,0.000000,0.176471,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
12,0.261905,0.00,0.000000,1.0,0.666667,0.25,1.000000,0.413060,0.111111,0.0,0.571429,0.0,1.000000,0.333333,0.150,0.000000,1.000000,0.150,0.222222,0.066667,0.176471,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
13,0.238095,0.25,0.000000,0.0,0.000000,0.00,0.333333,0.063560,0.777778,1.0,0.142857,0.0,1.000000,0.000000,0.250,0.666667,0.666667,0.175,0.388889,0.200000,0.411765,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
14,0.642857,0.50,0.333333,1.0,0.000000,0.50,0.000000,0.518273,0.222222,1.0,0.500000,0.0,0.333333,0.333333,0.600,0.333333,0.666667,0.175,0.388889,0.000000,0.411765,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
15,0.380952,0.75,1.000000,1.0,0.333333,0.00,0.666667,0.092628,0.333333,0.0,0.071429,0.0,0.666667,0.333333,0.350,0.500000,0.666667,0.175,0.166667,0.333333,0.411765,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
16,0.380952,0.00,0.000000,1.0,0.666667,0.25,1.000000,0.355292,0.000000,0.0,0.428571,0.0,0.666667,0.000000,0.175,0.166667,0.333333,0.150,0.111111,0.000000,0.235294,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
17,0.095238,0.00,0.333333,0.0,0.666667,0.25,0.666667,0.166509,0.000000,1.0,0.571429,0.0,0.000000,0.333333,0.100,0.500000,1.000000,0.075,0.111111,0.000000,0.117647,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
18,0.428571,0.75,1.000000,0.0,0.666667,0.50,0.666667,0.320432,0.333333,0.0,0.071429,0.0,0.000000,0.000000,0.250,0.000000,0.666667,0.175,0.388889,0.066667,0.411765,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
19,0.714286,0.75,0.666667,0.0,0.666667,0.00,0.000000,0.071511,0.888889,0.0,0.071429,0.0,1.000000,0.333333,0.250,0.500000,0.333333,0.200,0.111111,0.466667,0.352941,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
20,0.023810,0.25,0.666667,1.0,0.666667,0.00,0.000000,0.081253,0.111111,0.0,1.000000,1.0,0.666667,0.000000,0.025,0.666667,0.666667,0.025,0.055556,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
21,0.595238,0.50,0.000000,0.0,0.333333,1.00,0.666667,0.968036,0.777778,0.0,0.142857,0.0,1.000000,0.000000,0.525,0.333333,0.666667,0.400,0.666667,0.400000,0.823529,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
22,0.333333,0.75,0.666667,0.0,0.666667,0.25,0.000000,0.301001,0.111111,0.0,0.071429,0.0,0.666667,0.333333,0.200,0.333333,1.000000,0.200,0.388889,0.400000,0.176471,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
23,0.595238,0.50,1.000000,1.0,0.333333,0.25,1.000000,0.305161,0.333333,0.0,0.500000,0.0,0.666667,0.333333,0.175,0.833333,0.666667,0.050,0.111111,0.133333,0.117647,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
24,0.190476,0.50,0.666667,0.0,0.333333,0.25,1.000000,0.165771,0.777778,1.0,0.571429,0.0,0.666667,0.333333,0.125,0.333333,0.333333,0.050,0.111111,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
25,0.333333,0.25,0.666667,0.0,0.333333,0.25,0.333333,0.222170,0.111111,1.0,0.000000,0.0,1.000000,0.000000,0.325,0.333333,0.666667,0.325,0.666667,0.733333,0.529412,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
26,0.738095,0.75,0.666667,0.0,0.666667,0.00,0.000000,0.115956,0.111111,0.0,0.214286,0.0,1.000000,0.333333,0.250,0.500000,0.333333,0.225,0.333333,0.066667,0.235294,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
27,0.666667,0.50,0.666667,1.0,0.666667,0.50,1.000000,0.492838,0.444444,1.0,0.071429,0.0,0.333333,0.333333,0.325,0.833333,0.333333,0.250,0.333333,0.000000,0.176471,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
28,0.071429,0.00,0.666667,1.0,0.666667,0.00,0.000000,0.072196,0.111111,1.0,0.000000,0.0,1.000000,0.000000,0.050,1.000000,0.666667,0.050,0.111111,0.066667,0.117647,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
29,0.714286,0.00,0.333333,1.0,1.000000,0.25,0.333333,0.374460,0.333333,0.0,0.071429,0.0,1.000000,0.000000,0.300,0.500000,0.666667,0.050,0.111111,0.133333,0.117647,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
30,0.380952,0.75,0.666667,0.0,0.666667,0.25,1.000000,0.298999,0.111111,0.0,0.000000,0.0,1.000000,0.000000,0.350,0.333333,1.000000,0.350,0.611111,0.266667,0.647059,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
31,0.428571,0.00,0.333333,1.0,0.333333,0.25,1.000000,0.151501,0.111111,0.0,0.714286,1.0,1.000000,0.000000,0.250,0.333333,0.333333,0.250,0.055556,0.000000,0.470588,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
32,0.666667,0.00,0.000000,0.0,0.666667,0.50,0.666667,0.501211,0.555556,0.0,0.000000,0.0,1.000000,0.000000,0.700,0.500000,0.333333,0.050,0.111111,0.066667,0.117647,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
33,0.952381,0.75,0.666667,0.0,0.333333,0.50,0.000000,0.473881,0.777778,1.0,0.214286,0.0,1.000000,0.000000,0.775,0.000000,0.333333,0.250,0.500000,0.333333,0.529412,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
34,0.619048,0.75,1.000000,1.0,0.666667,0.25,1.000000,0.287309,0.222222,1.0,0.142857,0.0,1.000000,0.000000,0.225,0.833333,1.000000,0.100,0.111111,0.066667,0.176471,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
35,0.261905,0.75,0.333333,1.0,0.333333,0.50,0.666667,0.575355,0.111111,0.0,0.500000,0.0,0.666667,0.000000,0.250,0.333333,0.666667,0.250,0.111111,0.000000,0.411765,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
36,0.500000,0.00,0.333333,0.0,0.333333,0.75,1.000000,0.580411,0.000000,0.0,0.000000,0.0,0.000000,0.333333,0.525,0.333333,0.333333,0.500,0.500000,0.600000,0.352941,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
37,0.119048,0.25,1.000000,1.0,0.666667,0.00,1.000000,0.086256,0.111111,0.0,0.142857,0.0,0.666667,0.000000,0.125,1.000000,1.000000,0.125,0.111111,0.066667,0.235294,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
38,0.666667,0.25,0.666667,1.0,0.333333,0.50,1.000000,0.453397,0.111111,0.0,0.357143,0.0,1.000000,0.000000,0.225,0.500000,0.666667,0.225,0.444444,0.266667,0.411765,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
39,0.428571,0.75,0.666667,1.0,1.000000,0.00,1.000000,0.141074,0.444444,0.0,0.500000,0.0,1.000000,0.666667,0.100,0.333333,0.666667,0.025,0.000000,0.000000,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
450,0.547619,0.00,0.666667,0.0,0.666667,0.50,0.666667,0.496998,0.000000,1.0,0.142857,0.0,1.000000,0.333333,0.575,0.500000,1.000000,0.550,0.777778,0.866667,0.294118,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
451,0.976190,0.00,0.000000,0.0,0.333333,0.25,0.666667,0.235071,0.777778,0.0,0.000000,0.0,1.000000,0.000000,0.500,0.333333,0.333333,0.100,0.166667,0.066667,0.176471,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
452,0.666667,0.75,1.000000,1.0,1.000000,0.75,0.000000,0.871933,0.111111,0.0,0.285714,0.0,0.333333,0.000000,0.675,0.833333,0.000000,0.650,0.000000,0.000000,0.705882,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
453,0.428571,0.75,0.000000,0.0,0.666667,0.25,0.333333,0.435440,0.333333,1.0,0.357143,0.0,1.000000,0.000000,0.375,0.500000,0.666667,0.125,0.222222,0.000000,0.058824,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
454,0.404762,0.50,0.000000,1.0,1.000000,0.00,0.333333,0.074618,0.000000,0.0,0.142857,0.0,0.666667,0.333333,0.150,0.833333,0.666667,0.125,0.222222,0.000000,0.176471,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
455,0.357143,0.50,1.000000,1.0,0.666667,0.25,0.333333,0.107741,0.555556,0.0,0.285714,0.0,1.000000,0.666667,0.275,0.333333,0.333333,0.225,0.444444,0.066667,0.411765,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
456,0.380952,0.25,1.000000,0.0,0.000000,0.25,1.000000,0.264350,0.555556,0.0,0.071429,0.0,0.000000,0.000000,0.150,0.500000,0.666667,0.050,0.111111,0.133333,0.117647,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
457,0.309524,0.75,0.000000,1.0,0.666667,0.50,0.666667,0.376619,0.222222,0.0,0.142857,0.0,0.000000,1.000000,0.250,0.333333,0.666667,0.025,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
458,0.690476,0.75,0.000000,1.0,0.666667,0.50,0.333333,0.570827,0.111111,1.0,0.071429,0.0,1.000000,0.333333,0.250,0.333333,0.333333,0.250,0.388889,0.600000,0.529412,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
459,0.833333,0.25,1.000000,0.0,0.666667,1.00,0.666667,0.926646,0.333333,0.0,0.500000,0.0,0.333333,0.333333,0.650,1.000000,0.666667,0.175,0.388889,0.266667,0.411765,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
460,0.357143,0.50,1.000000,1.0,0.333333,0.50,1.000000,0.321748,0.444444,0.0,0.285714,0.0,0.666667,0.333333,0.225,0.333333,0.666667,0.075,0.111111,0.066667,0.117647,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
461,0.380952,0.75,1.000000,1.0,0.666667,0.25,0.000000,0.228383,0.444444,0.0,0.428571,0.0,0.666667,0.333333,0.275,0.500000,0.333333,0.175,0.055556,0.000000,0.411765,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
462,0.071429,0.25,0.000000,0.0,0.333333,0.00,0.666667,0.085097,0.111111,0.0,0.642857,1.0,0.666667,0.000000,0.050,0.333333,0.000000,0.050,0.111111,0.133333,0.117647,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
463,0.428571,0.50,0.666667,0.0,0.666667,0.50,0.666667,0.478515,0.111111,0.0,0.142857,0.0,0.333333,1.000000,0.425,0.333333,0.666667,0.425,0.777778,0.800000,0.470588,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
464,0.523810,0.50,0.666667,1.0,0.666667,0.25,1.000000,0.192312,0.111111,0.0,0.142857,0.0,0.666667,0.000000,0.225,0.666667,0.666667,0.225,0.444444,0.533333,0.470588,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
465,0.309524,0.75,0.000000,0.0,0.333333,0.25,1.000000,0.234808,0.111111,0.0,0.214286,0.0,0.000000,0.666667,0.325,0.500000,0.666667,0.300,0.388889,0.333333,0.411765,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
466,0.333333,0.75,1.000000,1.0,0.333333,0.25,1.000000,0.456556,0.888889,0.0,0.928571,1.0,0.333333,0.000000,0.200,0.166667,0.666667,0.025,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
467,0.285714,0.75,0.666667,1.0,0.666667,0.50,0.333333,0.433965,0.333333,0.0,0.071429,0.0,0.333333,0.333333,0.225,0.500000,0.666667,0.100,0.111111,0.066667,0.176471,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
468,0.476190,0.25,1.000000,1.0,0.666667,0.00,1.000000,0.036493,0.111111,1.0,0.857143,1.0,0.666667,0.333333,0.025,0.500000,0.666667,0.025,0.000000,0.000000,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
469,0.690476,0.75,0.666667,1.0,0.666667,0.25,0.333333,0.209005,0.777778,0.0,0.000000,0.0,1.000000,0.333333,0.100,0.500000,0.000000,0.025,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
470,0.428571,0.75,0.666667,1.0,0.666667,0.00,0.666667,0.079516,0.444444,0.0,0.714286,1.0,0.666667,0.000000,0.400,1.000000,0.666667,0.275,0.444444,0.200000,0.529412,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
471,0.309524,0.50,0.666667,1.0,1.000000,0.00,1.000000,0.093839,0.000000,0.0,0.071429,0.0,0.000000,0.333333,0.075,0.666667,0.666667,0.050,0.111111,0.133333,0.117647,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
472,0.261905,0.50,0.333333,0.0,0.666667,0.50,1.000000,0.349131,0.111111,0.0,0.785714,1.0,1.000000,1.000000,0.250,0.500000,0.333333,0.250,0.222222,0.066667,0.529412,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
473,0.357143,0.50,0.333333,1.0,0.333333,0.25,1.000000,0.193418,0.333333,0.0,0.214286,0.0,0.666667,0.000000,0.225,1.000000,0.333333,0.175,0.388889,0.000000,0.058824,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
474,0.404762,0.50,0.666667,1.0,0.333333,0.50,0.333333,0.487888,0.222222,0.0,0.500000,0.0,0.333333,0.333333,0.375,0.333333,1.000000,0.175,0.388889,0.400000,0.235294,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
475,0.428571,0.50,1.000000,1.0,0.666667,0.50,0.000000,0.385045,0.777778,1.0,0.142857,0.0,1.000000,0.333333,0.375,0.166667,0.666667,0.300,0.444444,0.333333,0.411765,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
476,0.761905,0.50,0.000000,1.0,0.666667,1.00,0.333333,0.905266,0.111111,0.0,0.000000,0.0,0.666667,0.333333,0.800,0.333333,0.666667,0.800,0.277778,0.666667,0.411765,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
477,0.333333,0.25,0.000000,1.0,0.000000,0.25,0.333333,0.301527,0.666667,0.0,0.285714,0.0,0.333333,0.000000,0.250,0.333333,0.666667,0.000,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
478,0.166667,0.00,0.000000,1.0,1.000000,0.00,0.000000,0.127172,0.777778,0.0,0.142857,0.0,0.666667,0.000000,0.150,0.500000,0.333333,0.100,0.166667,0.000000,0.058824,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
479,0.523810,0.50,1.000000,0.0,0.666667,0.25,0.666667,0.279831,0.111111,0.0,0.000000,0.0,0.000000,0.333333,0.250,0.333333,1.000000,0.250,0.500000,0.600000,0.235294,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
480,0.714286,0.75,1.000000,1.0,0.666667,0.00,0.666667,0.065824,0.444444,0.0,0.428571,0.0,0.000000,0.666667,0.325,0.333333,0.333333,0.000,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
481,0.666667,0.50,0.666667,0.0,0.666667,0.75,0.000000,0.844602,0.888889,0.0,0.857143,1.0,0.000000,0.000000,0.700,0.333333,0.666667,0.650,0.833333,1.000000,0.529412,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
482,0.190476,0.50,0.000000,0.0,0.666667,0.00,1.000000,0.098841,0.111111,0.0,0.785714,1.0,0.333333,0.666667,0.075,0.500000,0.000000,0.075,0.111111,0.000000,0.117647,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
483,0.380952,0.50,0.666667,1.0,0.333333,0.25,0.333333,0.183307,0.444444,0.0,0.000000,0.0,1.000000,0.666667,0.350,0.833333,1.000000,0.250,0.500000,0.066667,0.470588,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
484,0.404762,0.50,0.000000,0.0,0.666667,0.00,0.000000,0.056082,0.111111,1.0,0.071429,0.0,1.000000,0.333333,0.025,0.333333,0.666667,0.025,0.000000,0.000000,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
485,0.214286,0.00,0.333333,0.0,0.333333,0.25,0.666667,0.133281,0.111111,0.0,0.714286,1.0,1.000000,0.333333,0.225,0.833333,0.666667,0.225,0.444444,0.333333,0.470588,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
486,0.547619,0.75,0.333333,1.0,0.333333,1.00,1.000000,0.954818,0.333333,0.0,0.285714,0.0,0.333333,1.000000,0.575,0.333333,0.333333,0.525,0.333333,0.800000,0.352941,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
487,0.785714,0.50,1.000000,1.0,0.666667,1.00,0.333333,0.991996,0.444444,1.0,0.928571,1.0,0.000000,0.333333,0.775,0.833333,0.333333,0.725,0.555556,0.733333,0.588235,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
488,0.119048,0.00,0.000000,1.0,1.000000,0.00,0.666667,0.131438,0.111111,0.0,0.500000,0.0,1.000000,0.000000,0.050,0.500000,0.666667,0.050,0.111111,0.000000,0.117647,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
489,0.404762,0.75,0.666667,1.0,0.666667,0.25,0.666667,0.170616,0.111111,1.0,0.000000,0.0,0.333333,0.000000,0.225,0.500000,0.666667,0.225,0.333333,0.066667,0.058824,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0

In [44]:
from pandas.plotting import scatter_matrix
from sklearn import model_selection
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [45]:
classifier = []
classifier.append(("LogisticReg", LogisticRegression(solver='liblinear',multi_class='ovr')))
classifier.append(("DecisionTree", DecisionTreeClassifier(criterion ='entropy')))
classifier.append(("KNN", KNeighborsClassifier()))
classifier.append(("KernelSVM", SVC(gamma='auto')))
classifier.append(("NaiveBayes", GaussianNB()))
classifier.append(("RandomForest", RandomForestClassifier()))

In [46]:
seed = 0
results = []
names = []
for name, model in classifier:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_results = model_selection.cross_val_score(model, x_train, y_train,cv=kfold)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

LogisticReg: 0.870408 (0.028149)
DecisionTree: 0.810204 (0.027074)
KNN: 0.818367 (0.028425)
KernelSVM: 0.838776 (0.025734)
NaiveBayes: 0.695918 (0.031218)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RandomForest: 0.851020 (0.031018)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [47]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2, k='all')
fit = bestfeatures.fit(x,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x.columns)

#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(50,'Score'))  #print 10 best features

                                Specs          Score
7                       MonthlyIncome  127922.293694
14                  TotalWorkingYears     230.721618
17                     YearsAtCompany     142.100054
18                 YearsInCurrentRole     117.522596
20               YearsWithCurrManager     110.671534
0                                 Age      84.155277
9                            OverTime      63.845067
30       JobRole_Sales Representative      34.290268
32               MaritalStatus_Single      30.771669
13                   StockOptionLevel      25.268826
5                            JobLevel      24.939242
33   BusinessTravel_Travel_Frequently      15.816623
24      JobRole_Laboratory Technician      11.699495
27          JobRole_Research Director      10.978010
25                    JobRole_Manager       9.496136
26     JobRole_Manufacturing Director       9.126589
19            YearsSinceLastPromotion       7.601723
6                     JobSatisfaction       7.011947
2             EnvironmentSatisfaction       6.890594
22                   Department_Sales       6.694465
31              MaritalStatus_Married       6.597586
8                  NumCompaniesWorked       6.438654
4                      JobInvolvement       4.605616
21  Department_Research & Development       3.702916
15              TrainingTimesLastYear       3.085796
36      Distance_score_Short Distance       2.707266
23            JobRole_Human Resources       1.859753
12           RelationshipSatisfaction       1.332333
16                    WorkLifeBalance       1.085543
34       BusinessTravel_Travel_Rarely       1.047857
35      Distance_score_Moderately Far       1.028862
1                           Education       0.520642
3                              Gender       0.510087
29            JobRole_Sales Executive       0.447333
10                  PercentSalaryHike       0.235027
11                  PerformanceRating       0.000506
28         JobRole_Research Scientist       0.000152

In [48]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.linear_model import LogisticRegression as logreg
logreg=LogisticRegression()
logreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [49]:
ypred=logreg.predict(X1_test)
ypred

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [52]:
len(ypred)

490

In [53]:
len(y_test)

490

In [54]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [55]:
confusionmatrix=confusion_matrix(y_test, ypred)
confusionmatrix

array([[406,   5],
       [ 51,  28]], dtype=int64)

In [56]:
accuracyscore=accuracy_score(y_test, ypred)
accuracyscore

0.8857142857142857

In [57]:
report=classification_report(y_test,ypred)
print(report)

              precision    recall  f1-score   support

           0       0.89      0.99      0.94       411
           1       0.85      0.35      0.50        79

    accuracy                           0.89       490
   macro avg       0.87      0.67      0.72       490
weighted avg       0.88      0.89      0.87       490